CREATE TABLE world_data (
    Country VARCHAR(100),
    Density INT,
    Agricultural_Land_Percent DECIMAL(5,2),
    Land_Area_Km2 INT,
    Armed_Forces_Size INT,
    Birth_Rate DECIMAL(5,2),
    Co2_Emissions DECIMAL(10,2),
    CPI DECIMAL(6,2),
    CPI_Change_Percent DECIMAL(5,3),
    Fertility_Rate DECIMAL(4,2),
    Forested_Area_Percent DECIMAL(5,3),
    Gasoline_Price DECIMAL(5,3),
    GDP BIGINT,
    Gross_Primary_Education_Enroll_Percent DECIMAL(5,2),
    Gross_Tertiary_Education_Enroll_Percent DECIMAL(5,2),
    Infant_Mortality DECIMAL(5,2),
    Life_Expectancy INT,
    Maternal_Mortality_Ratio INT,
    Minimum_Wage DECIMAL(5,2),
    Out_of_Pocket_Health_Expenditure DECIMAL(5,2),
    Physicians_Per_Thousand DECIMAL(5,2),
    Population BIGINT,
	Labor_Force_Participation_Percent DECIMAL(5,2),
    Tax_Revenue_Percent DECIMAL(5,2),
    Total_Tax_Rate_Percent DECIMAL(5,2),
    Unemployment_Rate DECIMAL(5,2),
    Urban_Population BIGINT
);

SELECT *
from world_data;


CREATE TABLE energy_data (
    entity TEXT,
    year INTEGER,
    access_to_electricity_pct REAL,
    access_to_clean_fuels_pct REAL,
    renewable_capacity_per_capita REAL,
    financial_flows_usd BIGINT,
    renewable_energy_pct REAL,
    electricity_from_fossil_fuels REAL,
    electricity_from_nuclear REAL,
    electricity_from_renewables REAL,
    low_carbon_electricity_pct REAL,
    energy_per_capita_kwh REAL,
    energy_intensity_mj_per_gdp REAL,
    co2_emissions_kt BIGINT,
    renewables_pct_primary_energy REAL,
    gdp_growth REAL,
    gdp_per_capita REAL,
    population_density REAL,
    land_area_km2 BIGINT
);


SELECT *
FROM energy_data;




--1
/* 1 TWH generated per year
EXPECTED RESULT: TWH generated by each source, for each year from 2000 to 2020
I add up the Terawatt hours from the various sources, renewable and non-renewable, and group them by year.*/
SELECT
    year AS Anno, 
    SUM(electricity_from_renewables) AS TWH_da_rinnovabile,  
    SUM(electricity_from_nuclear) AS TWH_da_nucleare,
    SUM(electricity_from_fossil_fuels) AS TWH_da_combustibili_fossili, 
    SUM(electricity_from_renewables) + SUM(electricity_from_nuclear) AS TWH_da_rinnovabili_e_nucleare,  
    SUM(electricity_from_renewables) + SUM(electricity_from_nuclear) + SUM(electricity_from_fossil_fuels) AS TWH_totali 
FROM 
    energy_data
WHERE
    year BETWEEN 2000 AND 2020
GROUP BY 
    year
ORDER BY 
    year;






/* 2 Leaders in renewable electricity production.
EXPECTED RESULT: The top 10 countries that generated the most electricity from renewable sources,
the amount in TWh, and the percentage of the global total in TWh. */
WITH renewable_electricity_ranking AS (
    SELECT
        entity AS country,
        SUM(electricity_from_renewables) AS total_renewable_electricity
    FROM energy_data
    WHERE electricity_from_renewables IS NOT NULL
    GROUP BY entity
),
global_renewable_electricity_total AS (
    SELECT
        SUM(electricity_from_renewables) AS total_global_renewable_electricity
    FROM energy_data
    WHERE electricity_from_renewables IS NOT NULL
)
SELECT
    re.country,
    re.total_renewable_electricity,
    ROUND(
        (re.total_renewable_electricity / ge.total_global_renewable_electricity)::NUMERIC,
        2
    ) AS renewable_electricity_percentage
FROM renewable_electricity_ranking re
CROSS JOIN global_renewable_electricity_total ge
ORDER BY re.total_renewable_electricity DESC
LIMIT 10;





/* 3 Green leaders and their emissions
EXPECTED RESULT: Countries that have generated the most TWH from green sources in the last 20 years,
their CO2 emissions in 2023, and the percentage of total CO2 emissions.*/
-- Step 1: Total global CO₂ emissions in 2023
WITH total_global_co2 AS (
    SELECT
        SUM(Co2_Emissions) AS total_co2_emissions
    FROM world_data
),
top_renewable_countries AS (
    SELECT
        entity AS country,
        DENSE_RANK() OVER (ORDER BY SUM(electricity_from_renewables) DESC) AS renewable_rank
    FROM energy_data
    WHERE electricity_from_renewables IS NOT NULL
    GROUP BY entity
    HAVING COUNT(DISTINCT year) >= 10  -- Optional: ensure sufficient historical data
)
SELECT
    trc.country,
    trc.renewable_rank,
    wd.Co2_Emissions AS country_co2_emissions,
    tgc.total_co2_emissions,
    ROUND((wd.Co2_Emissions / tgc.total_co2_emissions) * 100, 2) AS co2_share_percent
FROM top_renewable_countries trc
JOIN world_data wd
    ON trc.country = wd.Country
CROSS JOIN total_global_co2 tgc
WHERE trc.renewable_rank <= 10
ORDER BY trc.renewable_rank ASC;







/* 4 Leading Countries - NUCLEAR
EXPECTED RESULT: The 10 countries with the highest nuclear energy production in the last 20 years,
TWH produced in 2000 and 2020*/
SELECT
    n2020.entity AS country,
    n2000.electricity_from_nuclear AS nuclear_energy_2000,
    n2020.electricity_from_nuclear AS nuclear_energy_2020,
    n2020.electricity_from_nuclear - n2000.electricity_from_nuclear AS nuclear_energy_growth
FROM energy_data n2000
JOIN energy_data n2020
    ON n2000.entity = n2020.entity
    AND n2000.year = 2000
    AND n2020.year = 2020
WHERE n2000.electricity_from_nuclear IS NOT NULL
  AND n2020.electricity_from_nuclear IS NOT NULL
ORDER BY nuclear_energy_2020 DESC
LIMIT 10;




/* 5 Developed and Nuclear Countries.
EXPECTED RESULT: The 10 most developed countries (highest GDP in 2023) and total TWH generated by nuclear sources in 2000 and 2020*/

--With the first CTE, the countries with the highest GDP are selected and the rank is assigned

-- Step 1: Rank countries by GDP in 2023
WITH gdp_ranking AS (
    SELECT
        Country AS country,
        RANK() OVER (ORDER BY GDP DESC) AS gdp_rank
    FROM world_data
    WHERE GDP IS NOT NULL
),

-- Step 2: Identify the first year with nuclear energy data for each country
first_year_nuclear AS (
    SELECT
        entity AS country,
        MIN(year) AS first_year
    FROM energy_data
    WHERE electricity_from_nuclear IS NOT NULL
    GROUP BY entity
),

-- Step 3: Retrieve nuclear energy data for both the first year and 2020
nuclear_energy_years AS (
    SELECT
        e.entity AS country,
        e.year,
        e.electricity_from_nuclear AS nuclear_energy_twh
    FROM energy_data e
    WHERE e.year = 2020
       OR (e.entity, e.year) IN (
           SELECT entity, MIN(year)
           FROM energy_data
           WHERE electricity_from_nuclear IS NOT NULL
           GROUP BY entity
       )
),

-- Step 4: Combine data from the first year and 2020 for each country
nuclear_development AS (
    SELECT
        y2020.country,
        yfirst.nuclear_energy_twh AS nuclear_energy_first_year,
        y2020.nuclear_energy_twh AS nuclear_energy_2020,
        y2020.nuclear_energy_twh - yfirst.nuclear_energy_twh AS nuclear_energy_growth
    FROM nuclear_energy_years yfirst
    JOIN nuclear_energy_years y2020
        ON yfirst.country = y2020.country
    JOIN first_year_nuclear fy
        ON yfirst.country = fy.country AND yfirst.year = fy.first_year
    WHERE y2020.year = 2020
)

-- Step 5: Combine GDP data with nuclear energy growth and filter top 10 countries
SELECT
    gdp.country,
    nd.nuclear_energy_first_year,
    nd.nuclear_energy_2020,
    nd.nuclear_energy_growth
FROM gdp_ranking gdp
LEFT JOIN nuclear_development nd
    ON gdp.country = nd.country
WHERE nd.nuclear_energy_first_year IS NOT NULL
  AND nd.nuclear_energy_2020 IS NOT NULL
ORDER BY gdp.gdp_rank
LIMIT 10;






-- 6 Financial Flow Effectiveness
/* EXPECTED RESULT: The top 10 most financed countries, along with the TWh from renewable sources and fossil fuels in 2000 and 2020.
The first CTE calculates the total financial flows (in USD) for each country */
WITH FinancialFlows AS (
    SELECT 
        entity AS country, 
        SUM("financial_flows_usd") AS total_flows
    FROM energy_data
    WHERE "financial_flows_usd" IS NOT NULL
          AND "financial_flows_usd" != 0
    GROUP BY entity
),

-- Identifying the first year with recorded values for electricity from renewable sources
FirstElectricityYear AS (
    SELECT 
        entity AS country, 
        MIN(year) AS first_year_electricity
    FROM energy_data
    WHERE "electricity_from_renewables" IS NOT NULL
          OR "electricity_from_fossil_fuels" IS NOT NULL
    GROUP BY entity
),

-- Retrieving the values for electricity from renewables and fossil fuels for the first year and 2020
ElectricityValues AS (
    SELECT 
        e.entity AS country, 
        MAX(CASE WHEN e.year = f.first_year_electricity THEN e."electricity_from_renewables" END) AS renewable_electricity_first_year,
        MAX(CASE WHEN e.year = 2020 THEN e."electricity_from_renewables" END) AS renewable_electricity_2020,
        MAX(CASE WHEN e.year = f.first_year_electricity THEN e."electricity_from_fossil_fuels" END) AS fossil_fuel_electricity_first_year,
        MAX(CASE WHEN e.year = 2020 THEN e."electricity_from_fossil_fuels" END) AS fossil_fuel_electricity_2020
    FROM energy_data e
    INNER JOIN FirstElectricityYear f 
        ON e.entity = f.country
    WHERE e."electricity_from_renewables" IS NOT NULL
          OR e."electricity_from_fossil_fuels" IS NOT NULL
    GROUP BY e.entity, f.first_year_electricity
)

-- Final query to retrieve the top 10 most financed countries and their electricity data
SELECT 
    f.country,
    RANK() OVER (ORDER BY f.total_flows DESC) AS financial_flows_rank,
    ev.renewable_electricity_first_year,
    ev.renewable_electricity_2020,
    ev.fossil_fuel_electricity_first_year,
    ev.fossil_fuel_electricity_2020
FROM FinancialFlows f
LEFT JOIN ElectricityValues ev ON f.country = ev.country
ORDER BY financial_flows_rank
LIMIT 10;




/* 7. Renewable Energy Generation Capacity Per Capita
EXPECTED RESULT: The 10 most financed countries, their renewable energy generation capacity per capita in 2000 and 2020.
As before, we select the most financed countries */

WITH FinancialFlows AS (
    SELECT
        entity AS country, 
        RANK() OVER (ORDER BY SUM("financial_flows_usd") DESC) AS financial_flows_ranking
    FROM energy_data
    WHERE "financial_flows_usd" IS NOT NULL
    GROUP BY entity 
),

-- Retrieve renewable energy generation capacity per capita for the years 2000 and 2020
RenewableCapacity AS (
    SELECT 
        entity AS country, 
        MAX(CASE WHEN year = 2000 THEN "renewable_capacity_per_capita" END) AS capacity_2000, 
        MAX(CASE WHEN year = 2020 THEN "renewable_capacity_per_capita" END) AS capacity_2020
    FROM energy_data
    WHERE "renewable_capacity_per_capita" IS NOT NULL
    GROUP BY entity 
)

-- Final query to select the desired data
SELECT 
    f.country, 
    f.financial_flows_ranking, 
    rc.capacity_2000 AS renewable_capacity_2000, 
    rc.capacity_2020 AS renewable_capacity_2020
FROM FinancialFlows f
LEFT JOIN RenewableCapacity rc
    ON f.country = rc.country
ORDER BY f.financial_flows_ranking 
LIMIT 10;




	